//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public string MaCTSP { get; set; }
        public decimal GiaSP { get; set; }
        public string KichCoSP { get; set; }
        public int TinhTrangSP { get; set; }
        public int SoLuongSP { get; set; }
        public string MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
