//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public string MaDT { get; set; }
        public int SoLuongBan { get; set; }
        public int TongDoanhThu { get; set; }
        public System.DateTime Ngay { get; set; }
        public string MaHD { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
