//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string MaGH { get; set; }
        public string HinhSP { get; set; }
        public string TenSP { get; set; }
        public string MoTaSanPham { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaSP { get; set; }
        public decimal ThanhTien { get; set; }
        public string MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
