USE [master]
GO
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'fashionDB')
DROP DATABASE [fashionDB]
GO
/****** Object:  Database [fashionDB]    Script Date: 4/29/2023 5:23:40 PM ******/
CREATE DATABASE [fashionDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fashionDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\fashionDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fashionDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\fashionDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [fashionDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fashionDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [fashionDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [fashionDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [fashionDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [fashionDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [fashionDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [fashionDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [fashionDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [fashionDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [fashionDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [fashionDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [fashionDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [fashionDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [fashionDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [fashionDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [fashionDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [fashionDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [fashionDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [fashionDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [fashionDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [fashionDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [fashionDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [fashionDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [fashionDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [fashionDB] SET  MULTI_USER 
GO
ALTER DATABASE [fashionDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [fashionDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [fashionDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [fashionDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [fashionDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [fashionDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [fashionDB] SET QUERY_STORE = OFF
GO
USE [fashionDB]
GO
/****** Object:  Table [dbo].[CTDONHANG]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTDONHANG](
	[MaDH] [char](10) NOT NULL,
	[SoLuongDat] [int] NULL,
	[DonGia] [numeric](12, 0) NULL,
	[MaKichCo] [char](10) NOT NULL,
	[MaSP] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTGIOHANG]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTGIOHANG](
	[MaGH] [char](10) NOT NULL,
	[TenSP] [nvarchar](50) NOT NULL,
	[HinhSP] [char](30) NULL,
	[SoLuong] [int] NULL,
	[DonGia] [numeric](12, 0) NOT NULL,
	[MaKichCo] [char](10) NOT NULL,
	[MASP] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaGH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTHOADON]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTHOADON](
	[MaHD] [char](10) NOT NULL,
	[SoLuong] [int] NULL,
	[DonGia] [numeric](12, 0) NULL,
	[ThanhTien] [decimal](12, 2) NULL,
	[MaSP] [char](10) NOT NULL,
	[MaKichCo] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DOANHTHU]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOANHTHU](
	[MaDT] [char](10) NOT NULL,
	[Ngay] [date] NULL,
	[SoLuongBan] [int] NULL,
	[TongDoanhThu] [decimal](12, 0) NULL,
	[MAHD] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONHANG]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONHANG](
	[MaDH] [char](10) NOT NULL,
	[NgayDatHang] [date] NULL,
	[NgayGiaoHang] [date] NULL,
	[PTThanhToan] [nvarchar](50) NOT NULL,
	[TrangThaiDH] [int] NULL,
	[TongTien] [decimal](12, 2) NOT NULL,
	[MaKH] [char](10) NOT NULL,
	[MaGH] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GIOHANG]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIOHANG](
	[MaGH] [char](10) NOT NULL,
	[ThanhTien] [decimal](12, 2) NOT NULL,
	[MaKH] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaGH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MaHD] [char](10) NOT NULL,
	[NgayLap] [date] NULL,
	[TongTien] [decimal](12, 2) NULL,
	[MaKH] [char](10) NOT NULL,
	[MaDH] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [char](10) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[CCCD] [char](12) NOT NULL,
	[SDT] [char](11) NULL,
	[Email] [char](50) NULL,
	[NgaySinh] [date] NOT NULL,
	[GioiTinh] [char](1) NOT NULL,
	[DiaChi] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CCCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SDT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KICHCOSP]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KICHCOSP](
	[MaSP] [char](10) NOT NULL,
	[MaKichCo] [char](10) NOT NULL,
	[SoLuong] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC,
	[MaKichCo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAISANPHAM]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAISANPHAM](
	[MaLoaiSP] [char](10) NOT NULL,
	[TenLoaiSP] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLoaiSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenLoaiSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MaSP] [char](10) NOT NULL,
	[TenSP] [nvarchar](50) NOT NULL,
	[HinhSP] [char](30) NULL,
	[MoTa] [nvarchar](255) NULL,
	[GiaSP] [numeric](12, 0) NOT NULL,
	[TinhTrangSP] [int] NULL,
	[MaLoaiSP] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 4/29/2023 5:23:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[MaKH] [char](10) NOT NULL,
	[Username] [char](50) NOT NULL,
	[UserPass] [char](20) NOT NULL,
	[UserRole] [char](2) NOT NULL,
	[TinhTrang] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTDONHANG]  WITH CHECK ADD  CONSTRAINT [FK_CTDONHANG_DONHANG] FOREIGN KEY([MaDH])
REFERENCES [dbo].[DONHANG] ([MaDH])
GO
ALTER TABLE [dbo].[CTDONHANG] CHECK CONSTRAINT [FK_CTDONHANG_DONHANG]
GO
ALTER TABLE [dbo].[CTDONHANG]  WITH CHECK ADD  CONSTRAINT [FK_CTDONHANG_SANPHAM] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTDONHANG] CHECK CONSTRAINT [FK_CTDONHANG_SANPHAM]
GO
ALTER TABLE [dbo].[CTGIOHANG]  WITH CHECK ADD  CONSTRAINT [FK_CTGIOHANG_GIOHANG] FOREIGN KEY([MaGH])
REFERENCES [dbo].[GIOHANG] ([MaGH])
GO
ALTER TABLE [dbo].[CTGIOHANG] CHECK CONSTRAINT [FK_CTGIOHANG_GIOHANG]
GO
ALTER TABLE [dbo].[CTGIOHANG]  WITH CHECK ADD  CONSTRAINT [FK_CTGIOHANG_SANPHAM] FOREIGN KEY([MASP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTGIOHANG] CHECK CONSTRAINT [FK_CTGIOHANG_SANPHAM]
GO
ALTER TABLE [dbo].[CTHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CTHOADON_HOADON] FOREIGN KEY([MaHD])
REFERENCES [dbo].[HOADON] ([MaHD])
GO
ALTER TABLE [dbo].[CTHOADON] CHECK CONSTRAINT [FK_CTHOADON_HOADON]
GO
ALTER TABLE [dbo].[CTHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CTHOADON_SANPHAM] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTHOADON] CHECK CONSTRAINT [FK_CTHOADON_SANPHAM]
GO
ALTER TABLE [dbo].[DOANHTHU]  WITH CHECK ADD  CONSTRAINT [FK_DOANHTHU_HOADON] FOREIGN KEY([MAHD])
REFERENCES [dbo].[HOADON] ([MaHD])
GO
ALTER TABLE [dbo].[DOANHTHU] CHECK CONSTRAINT [FK_DOANHTHU_HOADON]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONHANG_GIOHANG] FOREIGN KEY([MaGH])
REFERENCES [dbo].[GIOHANG] ([MaGH])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [FK_DONHANG_GIOHANG]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONHANG_USERS] FOREIGN KEY([MaKH])
REFERENCES [dbo].[USERS] ([MaKH])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [FK_DONHANG_USERS]
GO
ALTER TABLE [dbo].[GIOHANG]  WITH CHECK ADD  CONSTRAINT [FK_GIOHANG_USERS] FOREIGN KEY([MaKH])
REFERENCES [dbo].[USERS] ([MaKH])
GO
ALTER TABLE [dbo].[GIOHANG] CHECK CONSTRAINT [FK_GIOHANG_USERS]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_DONHANG] FOREIGN KEY([MaDH])
REFERENCES [dbo].[DONHANG] ([MaDH])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_DONHANG]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_USERS] FOREIGN KEY([MaKH])
REFERENCES [dbo].[USERS] ([MaKH])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_USERS]
GO
ALTER TABLE [dbo].[KICHCOSP]  WITH CHECK ADD  CONSTRAINT [FK_KICHCOSP_CTDONHANG] FOREIGN KEY([MaKichCo])
REFERENCES [dbo].[CTDONHANG] ([MaDH])
GO
ALTER TABLE [dbo].[KICHCOSP] CHECK CONSTRAINT [FK_KICHCOSP_CTDONHANG]
GO
ALTER TABLE [dbo].[KICHCOSP]  WITH CHECK ADD  CONSTRAINT [FK_KICHCOSP_CTGIOHANG] FOREIGN KEY([MaKichCo])
REFERENCES [dbo].[CTGIOHANG] ([MaGH])
GO
ALTER TABLE [dbo].[KICHCOSP] CHECK CONSTRAINT [FK_KICHCOSP_CTGIOHANG]
GO
ALTER TABLE [dbo].[KICHCOSP]  WITH CHECK ADD  CONSTRAINT [FK_KICHCOSP_CTHOADON] FOREIGN KEY([MaKichCo])
REFERENCES [dbo].[CTHOADON] ([MaHD])
GO
ALTER TABLE [dbo].[KICHCOSP] CHECK CONSTRAINT [FK_KICHCOSP_CTHOADON]
GO
ALTER TABLE [dbo].[KICHCOSP]  WITH CHECK ADD  CONSTRAINT [FK_KICHCOSP_SANPHAM] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[KICHCOSP] CHECK CONSTRAINT [FK_KICHCOSP_SANPHAM]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SANPHAM_LOAISANPHAM] FOREIGN KEY([MaLoaiSP])
REFERENCES [dbo].[LOAISANPHAM] ([MaLoaiSP])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SANPHAM_LOAISANPHAM]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_USERS_KHACHHANG] FOREIGN KEY([MaKH])
REFERENCES [dbo].[USERS] ([MaKH])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_USERS_KHACHHANG]
GO
USE [master]
GO
ALTER DATABASE [fashionDB] SET  READ_WRITE 
GO


USE [fashionDB]
GO

--THÊM DỮ LIỆU USERS (ADMIN ONLY)
INSERT INTO USERS(MaKH, Username, UserPass, UserRole, TinhTrang) VALUES ('ADMIN_01', 'admin01', 'admin@123', 'AD', 1);
INSERT INTO USERS(MaKH, Username, UserPass, UserRole, TinhTrang) VALUES ('ADMIN_02', 'admin02', 'admin@123', 'AD', 1);
INSERT INTO USERS(MaKH, Username, UserPass, UserRole, TinhTrang) VALUES ('ADMIN_03', 'admin03', 'admin@123', 'AD', 1);
INSERT INTO USERS(MaKH, Username, UserPass, UserRole, TinhTrang) VALUES ('ADMIN_04', 'admin04', 'admin@123', 'AD', 1);
select * from USERS

--THÔNG TIN NHÂN VIÊN ADMIN (SỬ DỤNG BẢNG KHÁCH HÀNG)
INSERT INTO KHACHHANG(MaKH, HoTen, CCCD, SDT, Email, NgaySinh, GioiTinh, DiaChi) 
VALUES ('ADMIN_01', N'Trần Lê Duy', '076820202381', '0904689418', 'trn.duyle@gmail.com', '2002/02/26', 'M', N'368/25A Tôn Đản, Phường 4, Quận 4, TP.HCM');
select * from KHACHHANG
